config/routes.rb
MusicWeek::Application.routes.draw do

  root :to => 'welcome#show'
  resources :signups
  resources :albums
  resources :albums do
    resources :songs, :only => [:create, :destroy]
  end
  match '/dashboard' => 'signups#index'
  match '/uploaded' => 'albums#uploaded'
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  resources :users
  resources :sessions
end

app/models/album.rb
class Album < ActiveRecord::Base
  attr_accessible :art, :artist, :name, :number_of_songs, :songs_attributes, :zip, :uploaded_by
  has_many :songs, :dependent => :destroy
  has_many :signups, :dependent => :destroy
  accepts_nested_attributes_for :songs
  after_create :import_all

  def import_all
    tag_songs
    import_album_tags
    import_cover
  end

  def uploader
    if uploaded_by
      user = User.find(uploaded_by)
      user.email if user
    end
  end

  def fetch_cover
    key = 'dd7362de3ee9247117b4d707413168d8'
    conn = Faraday.new(:url => 'http://ws.audioscrobbler.com') do |builder|
      builder.use Faraday::Request::UrlEncoded
      builder.use Faraday::Response::Logger
      builder.use Faraday::Adapter::NetHttp
    end
    response = conn.get "/2.0/?method=album.getinfo&api_key=#{key}&artist=#{artist.gsub(" ","+")}&album=#{name.gsub(" ","+")}"
    parse_art_xml(response.body)
    
  end

  def import_album_tags
    uri = songs.last.file_url
    Mp3Info.open(open(uri)) do |mp3|
      self.update_attributes(:name=> mp3.tag.album,
                             :artist => mp3.tag.artist)
    end
  end

  def import_cover
    self.update_attribute(:art, fetch_cover)
  end

  def tag_songs
    songs.each do |song|
      song.import_tags
    end
  end

private

  def parse_art_xml(response)
    xml = Nokogiri::XML(response)
    images = xml.xpath('//album/image')
    image = images.select {|image| image.attr('size') == 'large'}
    image[0].text
  end

end

app/models/signup.rb
class Signup < ActiveRecord::Base
  attr_accessible :user_id, :date, :album_id
  belongs_to :user
  belongs_to :album
  

  # def self.selectable(user_id)
  #   user= User.find(user_id)
  #   selectable = []
  #   date = Date.today
  #   7.times do
  #     if user.signups.where(date: date).blank? 
  #       selectable << date
  #     end
  #     date += 1
  #   end
  #   selectable
  # end


end

app/models/song.rb
require 'mp3info'
require 'open-uri'
require 'carrierwave'

class Song < ActiveRecord::Base
  attr_accessible :album_id, :length, :title, :file, :track_number, :remote_file_url
  belongs_to :album
  mount_uploader :file, FileUploader


  def import_tags
    uri = self.file_url
    Mp3Info.open(open(uri)) do |mp3|
        self.update_attributes(:title => mp3.tag.title,
                               :track_number => mp3.tag.tracknum)
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password, :password_confirmation
  has_many :signups
  has_many :albums, :through => :signups

  attr_accessor :password
  before_save :encrypt_password
  
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
  
  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  before_filter do
    redirect_to root_path unless current_user
  end

  def index
    @albums = Album.all
  end

  def show
    @album = Album.find(params[:id])
    @songs = @album.songs.sort_by(&:track_number)
  end

  def new
    render :layout => 'bare'
    @album = Album.new
  end

  def create
    @album = Album.new(params[:album])
    if @album.save
      redirect_to uploaded_path(:album_name => @album.name)
    else
      render :new
    end
  end

  def uploaded
    render :layout => 'bare'
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  helper_method :current_user

private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.authenticate(params[:email], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to albums_path, :notice => "Logged in!"
    else
      flash.now.alert = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged out!"
  end
end

app/controllers/signups_controller.rb
class SignupsController < ApplicationController
  
  before_filter do
    redirect_to root_path unless current_user
  end

  def new
    @signup = Signup.new
  end

  def show
    @signup = Signup.find(params[:id])
  end

  def create
    @signup = Signup.new(params[:signup])
    if @signup.save
      redirect_to root_url, :notice => "signup added!"
    else
      render :new
    end
  end

  def index
    @signups =current_user.signups if current_user
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  
  before_filter do
    redirect_to root_path unless current_user
  end

  def update
    @song = Song.find(params[:id])
    @song.update_attributes(params[:song])
    @song.save
    redirect_to album_path(@song.album)
    flash.now.alert = "song has been updated"
    @song.import_tags
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to root_url, :notice => "Signed up!"
    else
      render "new"
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def show
    redirect_to albums_path if current_user
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def link_to_add_fields(name, f, association)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + "_fields", f: builder)
    end
    link_to(name, '#', class: "add_fields", data: {id: id, fields: fields.gsub("\n", "")})
  end

  def todays_album_link
  	if current_user
  		album = current_user.signups.find_by_date(Date.today).album
  		link_to("Today's Album", album_path(album)).html_safe if album
  	end
  end

  def todays_album_or_nil
    if current_user
      todays_signup = current_user.signups.find_by_date(Date.today)
      todays_signup.album if todays_signup
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/signups_helper.rb
module SignupsHelper

	def signup_or_holder(date)
		signup = Signup.all.find {|signup| signup.date == date}
		if signup
	  	image_tag(signup.album.art, :class => "album").html_safe
	  else
	  	"Nothing on this day #{link_to("signup for an album", albums_path)}".html_safe
		end
	end

end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/albums/_form.html.erb
<%= nested_form_for Album.new, :html => {:multipart => true}  do |f| %>
  <p>add an album song by song</p>
  <%= f.hidden_field :uploaded_by,  { value: current_user.id} %>
  <%= f.fields_for :songs do |builder| %>
    <%= render 'song_fields', f: builder %>
  <% end %>

<%= link_to_add_fields "Add a Song", f, :songs %>

<br/>
<br/>
<p><%= f.submit "Submit" %></p>
<% end %>

app/views/albums/_play.html.erb
<div>
	<% if album %>
		<div class="span6">
		<h2><%= album.artist %> ~<%= album.name %></h2>
		<%= image_tag album.art, :class => "album" %>
		</div>
		<div class="span6">
		<audio class="mp3player" width="300" height="32" src="" controls="controls" data-current="" preload="auto" autoplay="false" autobuffer="">
		</audio>
		<a href="#" id="prev"><%= image_tag "back.png", :class=>"button" %></a>
		<a href="#" id="next"><%= image_tag "next.png", :class=>"button" %></a>
		<h2 id="nowplaying"></h2> 
		<% album.songs.each do |song| %>
		<a href="#" class="song" data-track="<%=song.track_number%>" data-song="<%=song.file_url%>" data-artist="<%=song.album.artist%>" data-title="<%=song.title%>"><%=image_tag("play.png", :class=>"button")%> <%=song.title%></a>
		</br>
		<% end %>
		</div>
	<% else %>
		<p class="nosignup">you didn't sign up for an album today (its not too late)</p>
	<% end %>
</div>

app/views/albums/_signup_modal.html.erb
<div class="modal hide fade" id="myModal">
  <div class="modal-header">
    <h3 id="modalheader"></h3>
  </div>
  <div class="modal-body">
  <%= form_for Signup.new do |f| %>
    <% if current_user %>
    <%= f.hidden_field :user_id, { value: current_user.id} %>
    <% end %>
    <%= f.hidden_field :album_id, :id =>"signup-album" %>
    <%= f.datepicker 'date', :dateFormat => "yy-mm-dd", :placeholder => "Select a Date", :minDate => -0, :maxDate => "+7D", :embed => true %>
  </div>
  <div class="modal-footer">
    <%= f.submit "Sign up!" %>
    <% end %>
  </div>
</div>

app/views/albums/_song_fields.html.erb
<fieldset>
  <%= f.file_field :file  %><br />
  <%= link_to "remove song", '#', class: "remove_fields" %>
<fieldset>

app/views/albums/index.html.erb
<div class="container">
  <div class="top-nav pull right">
    <h2>
      <%= link_to "add a new album", new_album_path, :target => "_blank", :class=>"popup pull-right" %>
    </h2>
  </div>

  <div id="slider-two" class="albumslider">
  	<% @albums.each do |album| %>
  		<div>
  		<%= image_tag album.art, :class =>"scrolleralbumart" %>
  			<h2><span><%= album.artist%></span></h2>
  			<h2 class="albumname"><%= album.name %></h2>
        <%#= link_to "Album Details", album_path(album) %>
        <p>Uploaded by: <%= album.uploader %> </p>
  			<a class="modallaunch btn" data-toggle="modal" href="#myModal" data-album-id="<%= album.id %>" data-album-name="<%= album.name %>">Sign up!</a>
  		</div>
  	<% end %>
  </div>

  <%= render partial: "signup_modal" %>

  <div class="slide-out-div-calendar">
    <a class="handle" href="http://link-for-non-js-users.html">Content</a>
    <%= render partial: "signups/signups" %>
  </div>

  <div class="slide-out-div-album">
    <a class="albumhandle" href="http://link-for-non-js-users.html">Content</a>
    <%= render partial: "play", :locals => { :album => todays_album_or_nil } %>
  </div>
</div>

app/views/albums/new.html.erb
<h1>Upload a New Album</h1>

<%= render partial: "form" %>

app/views/albums/show.html.erb
<div class="container">
	<div class="span6">
	<% @songs.each do |song| %>
	<h3><%= song.track_number %>. <%= song.title %></h3>
	</br>
	<% end %>
	</div>
</div>

app/views/albums/uploaded.html.erb
<h2><%= params["album_name"] %> has been uploaded!  Thanks!</h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TuneWeek</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jquery/1.4.3/jquery.min.js" %>  
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="user_nav" class="pull-right">
  <% if current_user %>
    Logged in as <%= current_user.email %>.
    <%= link_to "Log out", logout_path %>
  <% else %>
    <%= link_to "Sign up", signup_path %> or
    <%= link_to "log in", login_path %>
  <% end %>
</div>
<h1 class="brandheader">TuneWeek</h1>

<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>


<%= yield %>

</body>
</html>

app/views/signups/_signups.html.erb
<div id="signup-schedule">
  <table class="table-bordered table-striped signuptable">
    <thead>
      <tr>
        <th class="table-header">Today</th>
        <th class="table-header">Tomorrow</th>
        <th class="table-header"><%= (Date.today+2).strftime("%B #{(Date.today+2).day.ordinalize}") %></th>
        <th class="table-header"><%= (Date.today+3).strftime("%B #{(Date.today+3).day.ordinalize}") %></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td class="signup-cell"><%= signup_or_holder(Date.today) %></td>
        <td class="signup-cell"><%= signup_or_holder(Date.today+1) %></td>
        <td class="signup-cell"><%= signup_or_holder(Date.today+2) %></td>
        <td class="signup-cell"><%= signup_or_holder(Date.today+3) %></td>
      </tr>
    </tbody>
  </table>
</div>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p class="button"><%= f.submit %></p>
<% end %>

app/views/welcome/show.html.erb
<div class="welcome">
<h1><%= link_to "Sign up for an account", signup_path %></h1>
<h1><%= link_to "log in", login_path %></h1>

</div>

<div class="value">
<div class="container">
<h1>This will be the landing page for non logged in users</h1>
</div>
</div>